.TH "Matrix" 3 "Fri Jan 13 2023" "Version 1.0" "Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Matrix \- \fBMatrix\fP contain its number of rows and colums and a pointeur to its data (floats)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Matrix\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned short \fBn_cols\fP"
.br
.ti -1c
.RI "unsigned short \fBn_rows\fP"
.br
.ti -1c
.RI "float * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBMatrix\fP contain its number of rows and colums and a pointeur to its data (floats) 

.SH "Author"
.PP 
Generated automatically by Doxygen for Project from the source code\&.
