.TH "Vec2" 3 "Fri Jan 13 2023" "Version 1.0" "Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vec2 \- Vector containing 2 floats x,y\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Vec\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Vector containing 2 floats x,y\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Project from the source code\&.
